name: Node CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: |
        cd capstone_project/hello-world
        npm install
    - name: Run tests
      run: |
        cd capstone_project/hello-world 
        npm test
